
--- === hs._asm.clipmanager ===
---
--- Portions based on code found at https://github.com/victorso/.hammerspoon/blob/master/tools/clipboard.lua

-- Need to add parameter setting, menu, pasting, parameter and history saving

local module = {}

-- Technically not needed in hammerspoon, but good practice anyways
local menubar     = require "hs.menubar"
local timer       = require "hs.timer"
local settings    = require "hs.settings"
local pasteboard  = require "hs.pasteboard"
local hash        = require "hs.hash"

-- private variables and methods -----------------------------------------

local maxHistory        = settings.get("hs._asm.clipmanager.maxHistory")    or 25
local pollInterval      = settings.get("hs._asm.clipmanager.pollInterval")  or 1
local labelLength       = settings.get("hs._asm.clipmanager.labelLength")   or 40
local maxSize           = settings.get("hs._asm.clipmanager.maxSize")       or 102400 -- 100k
local honorClearContent = settings.get("hs._asm.clipmanager.honorClear")    or true
local pasteOnSelect     = settings.get("hs._asm.clipmanager.pasteOnSelect") or false

-- See http://nspasteboard.org
local ignoreTheseIdentifiers = {
    ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
    ["com.typeit4me.clipping"] = true,                 -- Transient : TypeIt4Me
    ["Pasteboard generator type"] = true,              -- Transient : Typinator
    ["com.agilebits.onepassword"] = true,              -- Confidential : 1Password
    ["org.nspasteboard.TransientType"] = true,         -- Universal, Transient
    ["org.nspasteboard.ConcealedType"] = true,         -- Universal, Concealed
    ["org.nspasteboard.AutoGeneratedType"] = true,     -- Universal, Automatic
}

local storedChangeCount = pasteboard.changeCount()
local storedClipHistory = settings.get("hs._asm.clipmanager.history") or {}


local clipboardChecker = function()
    if pasteboard.changeCount() > storedChangeCount then
        local clipboardContents = pasteboard.getContents()
        if clipboardContents then   -- we can do something with it
            table.insert(storedClipHistory, clipboardContents)
            storedClipHistory[maxHistory + 1] = nil
        end                         -- else we can't... yet.
        storedChangeCount = pasteboard.changeCount()
    end
end

local clipboardMonitorTimer = nil

-- Public interface ------------------------------------------------------

--- hs._asm.clipmanager.monitorClipboard([state]) -> state
--- Function
--- Sets or gets the status of the clipboard monitoring process.
---
--- Parameters:
---   * state  - if present and a boolean value, then the clipboard monitor is either turned on or turned off, depending upon the value of `state`.  If it is not present, or is not a boolean value, then the current running state of the clipboard monitor is returned.
---
--- Returns:
---   * state - the current (or changed) status of the clipboard monitoring process.
module.monitorClipboard = function(state)
    if type(state) == "boolean" then
        if state then
            if not clipboardMonitorTimer then
                clipboardMonitorTimer = timer.new(pollInterval, clipboardChecker):start()
            end
        else
            if clipboardMonitorTimer then
                clipboardMonitorTimer = timer.new(pollInterval, clipboardChecker):stop()
                clipboardMonitorTimer = nil
            end
        end
    end
    return (clipboardMonitorTimer ~= nil)
end

--- hs._asm.clipmanager.historySize() -> number
--- Function
--- Returns the number of items currently in the clipboard history.
---
--- Parameters:
---   * None
---
--- Returns:
---   * The number of items currently in the clipboard history.
module.historySize = function()
    return #storedClipHistory
end

-- Return Module Object --------------------------------------------------

return module
